### ISSUE TITLE
Website/App does not load upon first visit 

### ISSUE THREAD

**Issue by mpschr** [X-Hades-X/GeoML#1]
Reproduce: 

- Open Incognito in your Browser (Edge, Chrome, Brave, Firefox and Safari tested)
- enter on https://www.datascience.erni/de, select GeoML link

GeoML does not load.
![image](https://user-images.githubusercontent.com/1090105/220108958-716aeb9e-7d65-46a8-b97e-6e69c23fe698.png)

This is a critical issue

**Comment by X-Hades-X** [comment]
The anonymous credentials were not ready when loading the tasks. It now waits correctly when visiting the page the first time before loading the tasks.
